analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3409456,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 3381048,\\n  \\"organizationId\\"\: 3446011,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3381048\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
